---
  - name: Install build tools
    apt: name={{ item }} state=latest
    sudo: yes
    with_items:
        - 'gcc'
        - 'g++'
        - 'make'
        - 'build-essential'
        - 'git'
        - 'autoconf'
        - 'curl'

  - name: Install libtool
    apt: name=libtool state=latest

  - name: Install libssl
    apt: name=libssl-dev state=latest
