---

  - name: Install npm
    apt: name=npm state=latest

  - name: download nodejs
    get_url: url=http://nodejs.org/dist/{{ nodeVersion }}/node-{{ nodeVersion }}.tar.gz dest=/usr/local/src

  - name: build and install nodejs
    shell: cd /usr/local/src && tar xvf node-{{ nodeVersion }}.tar.gz && cd node-{{ nodeVersion }} && ./configure && make && make install

  - name: install bower grunt and forever
    shell: npm install -g bower grunt grunt-cli forever
