---
#- name: Install sudo
#  apt: pkg=sudo state=installed update_cache=yes cache_valid_time={{ sudoers_apt_cache_valid_time }}

- name: Create deploy user
  user: name={{ deploy_user }} shell=/bin/bash

- name: assign ssh key
  authorized_key: user={{ deploy_user }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Create sudoers.d directory
  file:
    path: /etc/sudoers.d
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Set includedir in sudoers
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"

- name: Create sudoers
  template:
    src: sudoers.d.j2
    dest: "/etc/sudoers.d/ansible"
    mode: 0440
    owner: root
    group: root
    validate: "/usr/sbin/visudo -cf %s"
  when: not sudoers_remove

- name: Remove sudoers
  file:
    path: "/etc/sudoers.d/{{ sudoers_filename }}"
    state: absent
  when: sudoers_remove

#- name: Disallow root SSH access
#  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
#  notify: restart ssh