---

  - name: Update apt-cache
    apt: update_cache=yes 

  - name: Install wget
    apt: name=wget state=latest

  - name: Install iptables
    apt: name={{ item }} state=latest
    with_items:
      - 'iptables'
      - 'iptables-persistent'




