---

  - name: Update apt-cache
    apt: update_cache=yes 

  - name: Install wget
    apt: name=wget state=latest

  - name: Install iptables
    apt: name={{ item }} state=latest
    with_items:
      - 'iptables'
      - 'iptables-persistent'

  - name: Edit /etc/sysctl.conf to disable ipv6
    lineinfile:  
        dest=/etc/sysctl.conf
        line="{{ item }}"
        state=present
    with_items:
        - '#disable IPV6'
        - 'net.ipv6.conf.all.disable_ipv6 = 1'
        - 'net.ipv6.conf.default.disable_ipv6 = 1'
        - 'net.ipv6.conf.lo.disable_ipv6 = 1'
        - 'net.ipv6.conf.lo.disable_ipv6 = 1'

  - name: Apply /etc/sysctl.conf changes
    shell: sysctl -p




